apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
      volumeMounts:
      - name: secret-volume
        mountPath: /data
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key 
