apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wordpress.toast 
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
