apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.mysql.nameSpace }}
  labels:
    app: {{ .Values.mysql.labels.app }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
{{- with .Values.mysql.labels }}
{{ toYaml . | indent 6  }}
{{- end }}            
  template:
    metadata:
      labels:
{{- with .Values.wordpress.labels }}
{{ toYaml . | indent 8  }}
{{- end }}              
    spec:
      containers:
      - name: {{ include "mysql.fullname" . }}
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mysql.fullname" . }}
              key: password        
{{- with .Values.mysql.resources }}
        resources:
{{ toYaml . | indent 10  }}
{{- end }}        
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql 
        ports:
        - containerPort: 3306
      volumes:
      - name: wordpress
      {{- if .Values.wordpress.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "mysql.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}        
