apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Values.wordpress.nameSpace }}
spec:
  ports:
  - port: {{ .Values.wordpress.service.externalPort }}
    targetPort: 80
{{- if (and (eq .Values.wordpress.service.type "NodePort") (not (empty .Values.wordpress.service.nodePort))) }}
    nodePort: {{ .Values.wordpress.service.nodePort }}
{{- end }}
  selector:
{{- with .Values.wordpress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  type: {{ .Values.wordpress.service.type }}
