apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        env:
         - name: WORDPRESS_DB_HOST
           value: "mysql.db.svc.cluster.local"
         - name: WORDPRESS_DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-password
               key: password
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html 
        ports:
        - containerPort: 80
      volumes:
      - name: wordpress
        persistentVolumeClaim:
          claimName: wp-pvc
