apiVersion: v1
kind: Pod
metadata:
  name: config-volume-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
      - name: nginx-volume
        mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-volume
    configMap:
      name: nginx-conf
