apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: password

