wordpress:
  replicaCount: 1
  image:
    repository: wordpress
    tag: "4.8-apache"    
  
  labels:
     app: wordpress
     stage: dev
  
  persistence:  
     enabled: false
     storageClass: sc-retain
     accessMode: ReadWriteOnce
     size: 10Gi      
  
  service:
    type: ClusterIP
    externalPort: 80
    nodePort: ""

  fullnameOverride: ""

mysql:
  db:
    password: test1234
