wordpress:
  nameSpace: web       
  replicaCount: 1

  image:
    repository: wordpress
    tag: "4.8-apache"    
  
  labels:
     app: wordpress
     stage: dev
  
  persistence:  
     enabled: true
     storageClass: sc-retain
     accessMode: ReadWriteOnce
     size: 10Gi      
  
  service:
    type: ClusterIP
    externalPort: 80
    nodePort: ""

  fullnameOverride: ""

mysql:
  nameSpace: db
  replicaCount: 1
  db:
    password: test1234

  persistence:
     enabled: true
     storageClass: sc-retain
     accessMode: ReadWriteOnce
     size: 10Gi
  
  labels:
     app: mysql
     stage: dev

  service:
    type: ClusterIP
    externalPort: 3306
    nodePort: "" 
