apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: pvc-nginx  
      containers:
      - name: nginx
        image: nginx:1.19
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
        ports:
        - name: nginx
          containerPort: 80
