apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
  namespace: prod
  labels:
    app: prod
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    resources:
      requests:
        cpu: 200m
        memory: 128Mi  
      limits:        
        cpu: 250m
        memory: 256Mi
  - name: busybox
    image: busybox
    command: ["sh"]
    args:
            - "-c"
            - "sleep 3600"        
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi      
    ports:
    - name: prod
      containerPort: 80
