wordpress:
  nameSpace: web       
  replicaCount: 1

  image:
    repository: wordpress
    tag: "4.8-apache"    
  
  labels:
     app: wordpress
     stage: dev
  
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1

  persistence:  
     enabled: true
     storageClass: sc-retain
     accessMode: ReadWriteOnce
     size: 10Gi      
  
  service:
    type: ClusterIP
    externalPort: 80
    nodePort: ""

  fullnameOverride: ""

mysql:
  nameSpace: db
  replicaCount: 1

  image:
    repository: mysql
    tag: "5.6"

  db:
    password: test1234
  
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

  persistence:
     enabled: true
     storageClass: sc-retain
     accessMode: ReadWriteOnce
     size: 10Gi
  
  labels:
     app: mysql
     stage: dev

  service:
    type: ClusterIP
    externalPort: 3306
    nodePort: ""

  fullnameOverride: ""
  
