apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
      - name: secret-volume
        mountPath: /confidential
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-key
