apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  special.how: very
  weather: sun
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  log_level: INFO
  log_max_vol: "500Mi"
  db_host: "mysql.db.svc.cluster.local:3306"

